[package]
name = "reflection_service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tonic = "0.7"
prost = "0.10"
tonic-reflection = "0.4"

[build-dependencies]
tonic-build = "0.7"

